apiVersion: v1
kind: Service  # Tipo de objeto: expone una app como un servicio en la red de Kubernetes
metadata:
  name: fastapi-service  # Nombre del servicio
spec:
  type: NodePort  # Exponer la app en un puerto accesible desde el exterior del clúster (para Minikube)
  selector:
    app: fastapi  # Selecciona los Pods con esta etiqueta
  ports:
    - port: 8000        # Puerto en el servicio (interno del clúster)
      targetPort: 8000   # Puerto dentro del contenedor
      nodePort: 30080  # Puerto accesible desde el exterior (usado por Minikube)