artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  steps:
    - name: download_file
      params:
        source_URL: parisrohan/credit-score-classification
        local_data_file: artifacts/data_ingestion/train.csv


data_validation:
  root_dir: artifacts/data_validation
  steps:
    - name: validate_types_columns
      params: 
        local_data_file: artifacts/data_ingestion/train.csv
        status_file: artifacts/data_validation/status.txt
        schema:
          ID: object
          Customer_ID: object
          Month: object
          Name: object
          Age: object
          SSN: object
          Occupation: object
          Annual_Income: object
          Monthly_Inhand_Salary: float64
          Num_Bank_Accounts: int64
          Num_Credit_Card: int64
          Interest_Rate: int64
          Num_of_Loan: object
          Type_of_Loan: object
          Delay_from_due_date: int64
          Num_of_Delayed_Payment: object
          Changed_Credit_Limit: object
          Num_Credit_Inquiries: float64
          Credit_Mix: object
          Outstanding_Debt: object
          Credit_Utilization_Ratio: float64
          Credit_History_Age: object
          Payment_of_Min_Amount: object
          Total_EMI_per_month: float64
          Amount_invested_monthly: object
          Payment_Behaviour: object
          Monthly_Balance: object
          Credit_Score: object
