artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  steps:
    - name: download_file
      params:
        source_URL: parisrohan/credit-score-classification
        local_data_file: artifacts/data_ingestion/train.csv


data_validation:
  root_dir: artifacts/data_validation
  steps:
    - name: validate_types_columns
      params: 
        local_data_file: artifacts/data_ingestion/train.csv
        status_file: artifacts/data_validation/status.txt
        schema:
          ID: object
          Customer_ID: object
          Month: object
          Name: object
          Age: object
          SSN: object
          Occupation: object
          Annual_Income: object
          Monthly_Inhand_Salary: float64
          Num_Bank_Accounts: int64
          Num_Credit_Card: int64
          Interest_Rate: int64
          Num_of_Loan: object
          Type_of_Loan: object
          Delay_from_due_date: int64
          Num_of_Delayed_Payment: object
          Changed_Credit_Limit: object
          Num_Credit_Inquiries: float64
          Credit_Mix: object
          Outstanding_Debt: object
          Credit_Utilization_Ratio: float64
          Credit_History_Age: object
          Payment_of_Min_Amount: object
          Total_EMI_per_month: float64
          Amount_invested_monthly: object
          Payment_Behaviour: object
          Monthly_Balance: object
          Credit_Score: object


data_transformation:
  root_dir: artifacts/data_transformation
  steps:
    - name: read_file_data
      params:
        local_data_file: artifacts/data_ingestion/train.csv
    - name: transform_target
      params:
        target_column: CREDIT_SCORE
        category: Poor
    - name: train_test_splitting
      params:
        test_size: 0.25
        stratify_col: CREDIT_SCORE
    - name: build_preprocess_ct
      params:
        dict_steps:
          prep_cat:
            columns:
              - OCCUPATION
            steps:
              - name: mb_clean_text
                params:
                  replace_value: Missing
              - name: mb_woe_encoder
                params: {}
          prep_num:
            columns:
              - MONTHLY_INHAND_SALARY
              - NUM_BANK_ACCOUNTS
              - NUM_CREDIT_CARD
              - INTEREST_RATE
              - DELAY_FROM_DUE_DATE
              - NUM_CREDIT_INQUIRIES
              - CREDIT_UTILIZATION_RATIO
              - TOTAL_EMI_PER_MONTH
            steps:
              - name: mb_simple_imputer
                params: {}
              - name: mb_standard_scaler
                params: {}
          prep_cat_num:
            columns:
              - AGE
              - ANNUAL_INCOME
              - NUM_OF_LOAN
              - NUM_OF_DELAYED_PAYMENT
              - CHANGED_CREDIT_LIMIT
              - OUTSTANDING_DEBT
              - AMOUNT_INVESTED_MONTHLY
              - MONTHLY_BALANCE
            steps:
              - name: mb_clean_text_number
                params: {}


model_trainer:
  root_dir: artifacts/model_trainer
  steps:
    - name: read_file_train
      params:
        train_file: artifacts/data_transformation/train.csv
        target_column: CREDIT_SCORE
    - name: load_pl_preprocess
      params:
        pl_preprocess_path: artifacts/data_transformation/pl_preprocess.joblib
    - name: create_model
      params:
        model: XGBClassifier
        dict_params:
          objective: binary:logistic
          n_estimators: 50
          max_depth: 7
          random_state: 202502
    - name: build_pipeline
      params: {}
    - name: train
      params:
        model_name: XGBClassifier
        version: 1.0


model_evaluation:
  root_dir: artifacts/model_evaluation
  steps:
    - name: read_files
      params:
        train_data_path: artifacts/data_transformation/train.csv
        test_data_path: artifacts/data_transformation/test.csv
        target_column: CREDIT_SCORE
    - name: log_into_mlflow
      params:
        path_model: artifacts/model_trainer
        local_metrics_file: artifacts/model_evaluation/metrics.json
        model_name: XGBClassifier
        version: 1.0


production:
  model_name: XGBClassifier
  model_alias: production
