version: 1
disable_existing_loggers: False

formatters:
  minimal:
    format: "%(message)s"
  detailed:
    format: "%(asctime)s - %(levelname)s - [%(name)s:%(filename)s:%(funcName)s:%(lineno)d] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: minimal
    stream: ext://sys.stdout

  debug_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: ./logs/debug.log
    maxBytes: 10485760
    backupCount: 5

  info_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: ./logs/info.log
    maxBytes: 10485760
    backupCount: 5

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: ./logs/error.log
    maxBytes: 10485760
    backupCount: 5

loggers:
  databank_mlops:
    level: DEBUG
    handlers: [console, info_file, debug_file, error_file]
    propagate: False

root:
  level: INFO
  handlers: [console]