name: Reproducir pipeline DVC con DagsHub

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}   
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Install CML
        uses: iterative/setup-cml@v2

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'